src/contacto/urls.py
from django.urls import path
from .views import Contactar

app_name = "contacto"

urlpatterns = [
    path('contactar/',Contactar.as_view(), name = 'contactar')
]

src/core/urls.py
from django.urls import path, include
from core import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.indexView, name = 'index'),
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('acercade/', views.acercadeView, name = 'acercade'),
    path ('defi/', views.defiView, name= 'defi'),
    path ('blockchains/', views.blockView, name='blockchains'),
    path ('tokens/', views.tokensView, name='tokens'),
    path ('trading/', views.tradingView, name='trading'),
    path('contacto/', include('contacto.urls')),
]

urlpatterns += staticfiles_urlpatterns ()

src/publicaciones/urls.py
from django.contrib import admin
from django.urls import path
from publicaciones import views
from .views import PostearView

app_name = 'publicaciones'

urlpatterns = [
    path('publicaciones/', views.VerPublicaciones.as_view(), name = 'publicaciones'),
   # path('postear/', PostearView.as_view(), name='add_post'),
    path('postear/', PostearView.as_view(), name='postear'),
    path('editar-post/<int:pk>', views.EditarPost.as_view(), name = 'editar-post'),
    path('eliminar-post/<int:pk>', views.EliminarPost.as_view(), name = 'eliminar-post'),
    path('detalle-post/<int:pk>', views.PostDetalle.as_view(), name = 'detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComentarioView.as_view(), name = 'borrar-comentario'),
    path('editar-comentario/<int:pk>', views.EditarComentarioView.as_view(),name = 'editar-comentario' ),
    path('agregar_categoria/', views.AgregarCategoriaView.as_view(), name= 'agregar_categoria'),
    
]

src/contacto/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Contacto(models.Model):
    autor = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'mensaje_usuario')
    asunto = models.CharField(max_length=150)
    mensaje = models.TextField()
    fecha = models.DateField(auto_now_add= True)

    def __str__(self):
        return self.asunto + '-' + self.autor.username

src/publicaciones/models.py
from django.db import models
from usuarios.models import User
# from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

#Esta clase crea una tabla para las categorías

class Categoria(models.Model):
    nombre = models.CharField(max_length= 255)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('publicaciones:publicaciones')

#Esta clase crea una tabla para las publicaciones
class Publicaciones(models.Model):
    fecha = models.DateField(auto_now_add= True)
    update = models.DateField(auto_now_add= True)
    titulo = models.CharField(max_length= 255)
    post = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete = models.SET_NULL, null = True, blank = True, related_name = 'posteos_categoria')
    creador = models.ForeignKey(User, on_delete=models.SET_NULL, null = True, blank = True, related_name='posteos_creador')
    imagen_url = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return self.titulo + '-' + self.creador.username
    
    def get_absolute_url(self):
        return reverse('publicaciones')
        
    

class Comentario(models.Model):
    texto = models.TextField()
    fecha = models.DateField(auto_now_add= True)
    post = models.ForeignKey(Publicaciones, on_delete= models.CASCADE, related_name= 'comentarios')
    autor = models.ForeignKey(User, on_delete= models.CASCADE, related_name= 'comentarios_autor')


    def __str__(self):
        return self.post.titulo + '-' + self.autor.first_name
    
 


    
        

src/contacto/forms.py
from django import forms
from .models import Contacto

class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['asunto', 'mensaje']

src/publicaciones/forms.py
from django import forms
from.models import Publicaciones,Comentario, Categoria



"""class PostForm(forms.ModelForm):
    class Meta:
     model=Publicaciones
     fields=['categoria','titulo','post']
     labels={
        'titulo':'',
        'post':'',
        'categoria':'',
    }

    widgets={
                      
            'titulo': forms.TextInput(attrs={'placeholder':'aca va el titulo','class':'form-control'}),

            'post':forms.TextInput(attrs={'placeholder':'escribi algo...','class':'form-control'}),

            'categoria':forms.Select(attrs={'class':'form-select', 'placeholder':'Categoria'}),          

    }
"""
class PostForm(forms.ModelForm):
      class Meta:
            model = Publicaciones
            fields = ('categoria', 'titulo', 'post', 'imagen_url')

            widgets = {
                  'titulo': forms.TextInput(attrs={'class': 'form-control'}),
                  'categoria': '',
                  'post': forms.Textarea(attrs={'class': 'form-control'}),
                  'imagen_url': forms.URLInput(attrs={'class': 'form-control'}),	
                  }


class ComentarioForm(forms.ModelForm):

    class Meta:
      model=Comentario
      fields =  ['texto']

    widgets = {
        'texto' : forms.TextInput(attrs={'placeholder':'Escribe aqui tu comentario', 'class': 'form-control'}),
    }

class CategoriaForm(forms.ModelForm):
     class Meta:
          model = Categoria
          fields = ['nombre']

src/contacto/views.py
from django.shortcuts import render
from django.urls import reverse

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from .models import Contacto
from .forms import ContactoForm


class Contactar(LoginRequiredMixin, CreateView):
    model = Contacto

    template_name = 'contactar.html'

    form_class = ContactoForm

    def get_success_url(self):
        return reverse('index')
    
    def form_valid(self, form):
        f = form.save(commit=False)
        f.autor_id = self.request.user.id
        return super().form_valid(f)

src/publicaciones/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Publicaciones, Comentario, Categoria
from .forms import PostForm, ComentarioForm, CategoriaForm
from core.mixins import SuperUsuarioAutorMixin, ColaboradorMixin
from django.db.models import Q

# View basada en una clase que renderiza las publicaciones
class VerPublicaciones(ListView):
    model = Publicaciones
    template_name = 'publicaciones.html'
    context_object_name = 'posteos'
    #cats = Categoria.objects.all()

                
    def get_context_data(self, *args, **kwargs):
       # menu_categoria = Categoria.objects.all()
        contexto = super().get_context_data(**kwargs)
        contexto['categorias']=Categoria.objects.all
        return contexto
        
        
#def categoriaListView(request):
      #menu_categoria_list = Categoria.objects.all()
      #return render(request, 'categoria_list.html', {'menu_categoria_list':menu_categoria_list})

#def categoriaView(request, cats):
      #category_posts = Publicaciones.objects.filter(categoria=cats.replace('-', ' '))
      #return render(request, 'categoria.html', {'cats':cats.replace('-', ' ').title(), 'category_posts':category_posts})



    def get_queryset(self):
        queryset = super().get_queryset()
        

        #Filtrando por categoria
        categoria_seleccionada = self.request.GET.get('categoria')
        if categoria_seleccionada:
            queryset = queryset.filter(categoria = categoria_seleccionada)
        

        # Ordenando por distintos criterios
        orden = self.request.GET.get('orderby')
        if orden:
            if orden == 'fecha_asc':
                queryset = queryset.order_by('fecha')
            elif orden == 'fecha_desc':
                queryset = queryset.order_by('-fecha')
            elif orden == 'alf_asc':
                queryset = queryset.order_by('titulo')
            elif orden == 'alf_desc':
                queryset = queryset.order_by('-titulo')


        return queryset

                


# View que permite ver los detalles de una publicacion
class PostDetalle(LoginRequiredMixin, DetailView):
    template_name = 'detalle-post.html'
    model = Publicaciones
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        menu_categoria = Categoria.objects.all()
        contexto = super().get_context_data(**kwargs)
        contexto['formulario_comentario'] = ComentarioForm()
        contexto["menu_categoria"] = menu_categoria
        return contexto

    def post(self, request, pk):
        if not self.request.user.is_authenticated:
            return reverse('usuarios:login')

        publicacion = self.get_object()
        form = ComentarioForm(request.POST)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.autor = self.request.user
            comentario.post = publicacion
            comentario.save()
        return super().get(request)

class AgregarCategoriaView(LoginRequiredMixin, CreateView):
	model = Categoria
	template_name = 'agregar_categoria.html'
	fields = '__all__'
        

        
# View que crea posteos nuevos
class Postear(LoginRequiredMixin, ColaboradorMixin, CreateView):
    model = Publicaciones
    template_name = 'postear.html'
    form_class = PostForm
    
    def get_success_url(self):
        return reverse('publicaciones:postear.html')
    
    def form_valid(self, form):
        f = form.save(commit=False)
        f.creador_id = self.request.user.id
        return super().form_valid(f)
       
   
class PostearView(LoginRequiredMixin, ColaboradorMixin, CreateView):
        
    def get(self, request):
        form = PostForm()
        return render(request, 'postear.html', {'form': form})

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.creador_id = request.user.id
            post.save()
            return redirect('publicaciones:publicaciones')
        return render(request, 'postear.html', {'form': form})


#	model = Publicaciones
#	form_class = PostForm
#	template_name = 'postear.html'
#	#fields = ('title', 'body')

# View que actualiza una publicacion ya existente
class EditarPost(LoginRequiredMixin, SuperUsuarioAutorMixin, ColaboradorMixin, UpdateView):
    model = Publicaciones
    template_name = 'editar-post.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')

# View que elimina un posteo
class EliminarPost(LoginRequiredMixin, SuperUsuarioAutorMixin, DeleteView):
    template_name = 'eliminar-post.html'
    model = Publicaciones

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')



class BorrarComentarioView(LoginRequiredMixin, SuperUsuarioAutorMixin, DeleteView):
    model = Comentario
    template_name = 'borrar-comentario.html'

    def get_success_url(self):
        return reverse('publicaciones:detalle-post', args=[self.object.post.id])
    

class EditarComentarioView(LoginRequiredMixin, SuperUsuarioAutorMixin, UpdateView):
    model = Comentario

    template_name = 'editar-comentario.html'

    form_class = ComentarioForm

    def get_success_url(self):
        return reverse('publicaciones:detalle-post', args=[self.object.post.id])

    

src/templates/agregar_categoria.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}


	<h1>Agregar Categoria</h1>
	<br/><br/>

	<div class="form-group">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-secondary">Agregar</button>
	</div>






{% endblock contenido %}
    

src/templates/borrar-comentario.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    

    
        <!-- Page content -->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content -->
                    <article>
                        <!-- ... Rest of the article ... -->
                    </article>
                    <!-- Comments section -->
                    <section class="mb-5">
                        <!-- ... Rest of the comments section ... -->

                        <!-- Formulario para eliminar un comentario -->
                        <form method="post">
                            {% csrf_token %}
                            <p>Estas a punto de eliminar el comentario</p>
                            <button type="submit" class="custom-button">Eliminar</button>
                        </form>
                    </section>
                </div>
                <!-- Side widgets -->
                <div class="col-lg-4">
                    <!-- ... Rest of the side widgets ... -->
                </div>
            </div>
        </div>

        <!-- Footer -->
      
        <!-- Bootstrap core JS -->
        <script src=""></script>
        <!-- Core theme JS -->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>
{% endblock contenido %}

src/templates/categoria.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
<h1>{{cats}}</h1>

<ul>
{% for post in category_posts %}
<div class="card m-5">
    <div class="card-header">
      {{post.fecha}}
    </div>
    <div class="card-body">
      <h5 class="card-title">{{post.titulo}}</h5>
      <p class="card-text">{{post.post|truncatechars:400}}</p>
      <p class="card-text">{{post.categoria}}</p>
      <p class="card-text">{{post.creador}}</p>
      
    
      {% if user.is_staff %}
                              <a class="btn btn-secondary" href="{% url 'publicaciones:editar-post' post.pk %}" role="button">Editar</a>
                              <a class="btn btn-danger" href="{% url 'publicaciones:eliminar-post' post.pk %}" role="button">Eliminar</a>
                   
                              {% endif %}
                            </div>
                          </div>
{% endfor %}
</ul> 




{% endblock contenido %}
    

src/templates/contacto.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
  

  
<!-- Bootstrap 5 Contact Form Snippet -->

<div class="container px-5 my-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card border-0 rounded-3 shadow-lg">
          <div class="card-body p-4">
            <div class="text-center">
              <div class="h1 fw-light">¡Ponte en contacto!</div>
              <p class="mb-4 text-muted">Escribe un mensaje y ponte en contacto con el equipo</p>
              
            </div>
  
            <!-- * * * * * * * * * * * * * *
            // * * SB Forms Contact Form * *
            // * * * * * * * * * * * * * * *
  
            // This form is pre-integrated with SB Forms.
            // To make this form functional, sign up at
            // https://startbootstrap.com/solution/contact-forms
            // to get an API token!
            -->
  
            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
  
              <!-- Name Input -->
              <div class="form-floating mb-3">
                <input class="form-control" id="name" type="text" placeholder="Name" data-sb-validations="required" />
                <label for="name">Nombre</label>
                <div class="invalid-feedback" data-sb-feedback="name:required">Name is required.</div>
              </div>
  
              <!-- Email Input -->
              <div class="form-floating mb-3">
                <input class="form-control" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                <label for="emailAddress">Correo electrónico</label>
                <div class="invalid-feedback" data-sb-feedback="emailAddress:required">Email Address is required.</div>
                <div class="invalid-feedback" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
              </div>
  
              <!-- Message Input -->
              <div class="form-floating mb-3">
                <textarea class="form-control" id="message" type="text" placeholder="Message" style="height: 10rem;" data-sb-validations="required"></textarea>
                <label for="message">Mensaje</label>
                <div class="invalid-feedback" data-sb-feedback="message:required">Message is required.</div>
              </div>
  
              <!-- Submit success message -->
              <div class="d-none" id="submitSuccessMessage">
                <div class="text-center mb-3">
                  <div class="fw-bolder">Form submission successful!</div>
                  <p>To activate this form, sign up at</p>
                  <a href="https://startbootstrap.com/solution/contact-forms"></a>
                </div>
              </div>
  
              <!-- Submit error message -->
              <div class="d-none" id="submitErrorMessage">
                <div class="text-center text-danger mb-3">Error sending message!</div>
              </div>
  
              <!-- Submit button -->
              <div class="d-grid">
                <button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Enviar</button>
              </div>
            </form>
            <!-- End of contact form -->
             
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- CDN Link to SB Forms Scripts -->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  
  {% endblock contenido %}

src/templates/editar-comentario.html
<!DOCTYPE html>
<html>
<head>
  <title>Editar Comentario</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f0f0f0;
    }

    .custom-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 15px;
      max-width: 400px; /* Reducimos el ancho máximo del formulario */
      width: 100%;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Estilos para redondear los inputs de texto */
    .form-group input[type="text"],
    .form-group input[type="email"], /* Agregamos el selector para el input de correo electrónico */
    .form-group input[type="password"] {
      border-radius: 5px;
      border: 1px solid #ccc;
      padding: 2px; /* Reducimos el espacio interior de los inputs */
      width: 40%;
    }

    /* Estilo para redondear el botón y cambiar el color */
    .btn {
      border-radius: 5px;
      padding: 2px; /* Reducimos el espacio interior del botón */
    }

    /* Cambiamos el color del botón a un azul más claro */
    .btn-primary {
      background-color: #0062E6;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="custom-container">
    <div class="form-container">
      <h2 class="text-center mb-4">Editar Comentario</h2>
      <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group">
            {% if field.name == 'email' %}
              <label for="{{ field.id_for_label }}">Correo electronico</label>
            {% else %}
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {% endif %}
            {{ field }}
            <div class="invalid-feedback">
              {{ field.errors }}
            </div>
          </div>
        {% endfor %}

        <!-- Usamos la clase .btn-primary para cambiar el color del botón -->
        <button type="submit" class="btn btn-primary btn-block mt-3">Guardar</button>
      </form>
    </div>
  </div>
</body>
</html>
    

src/templates/editar-post.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    



    <!-- Page content-->
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <!-- Edit post content-->
                <article>
                    <h2>Editar Publicación</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-dark">Guardar cambios.</button>
                    </form>
                </article>
            </div>
            <!-- Side widgets (rest of the content)-->
            <div class="col-lg-4">
                <!-- ... Rest of the side widgets ... -->
            </div>
        </div>
    </div>
    <!-- Footer-->
  
    
    <!-- Bootstrap core JS-->
    <script src=""></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js'%}"></script>


{% endblock contenido %}

src/templates/eliminar-post.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}



                    <!-- Delete post form -->
                    <form method="post">
                        <p>Estas a punto de eliminar la publicación!!</p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">Eliminar</button>
                    </form>
                </article>
                <!-- Comments section-->
                <!-- ... Rest of the comments section ... -->
            </div>
            <!-- Side widgets (rest of the content)-->
            <div class="col-lg-4">
                <!-- ... Rest of the side widgets ... -->
            </div>
        </div>
    </div>
    <!-- Footer-->
   
    <!-- Bootstrap core JS-->
    <script src=""></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js'%}"></script>




{% endblock contenido %}

src/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}

       <!-- Preview image figure-->
       <figure class="nosotros"><img class="img-fluid rounded" src="https://i.imgur.com/LzrAt5d.png"  alt="..." /></figure>
       <!-- Footer-->
       <footer class="py-5 bg-dark">
         <div class="container"><p class="m-0 text-center text-white">GRUPO 1 - INFORMATORIO 2023</p></div>
     </footer>
     <!-- Bootstrap core JS-->
     <script src=""></script>
     <!-- Core theme JS-->
     <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>

{% endblock contenido %}

src/templates/postear.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    

        <!-- Formulario para crear una nueva publicación -->
    
        <h5>PUBLICAR</h5>

        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-secondary">Publicar</button>
                </div>

   
        <!-- <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark">Postear!</button>
        </form> -->

        <!-- Footer -->
       
        <!-- Bootstrap core JS -->
        <script src=""></script>
        <!-- Core theme JS -->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>
{% endblock contenido %}

src/templates/publicaciones.html
{% extends 'base.html' %}
{% load static %}

                   
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Categorias
    </button>
    <ul class="dropdown-menu">
        
{% for categoria in menu_categoria %}
    <a class="dropdown-item" href="#">{{ categoria }}</a>
    {% endfor %}    
</ul>

</div>



                   
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Categorias
    </button>
    <ul class="dropdown-menu">
        
{% for categoria in menu_categoria %}
    <a class="dropdown-item" href="#">{{ categoria }}</a>
    {% endfor %}    
</ul>

</div>



{% block contenido %}

    <form action="" method="get">

        <select name="categoria" id="">

            <option value="">Todas</option>
            {% for categoria in categorias %}
            <option value="{{categoria.id}}">{{categoria.nombre}}</option>
            {% endfor %}

        </select>

        <select name="orderby" id="">
            <option value="">Ordenar por</option>
            <option value="fecha_asc">Fecha ascendente</option>
            <option value="fecha_desc">Fecha descendente</option>
            <option value="alf_asc">Alfabeticamente ascendente</option>
            <option value="alf_desc">Alfabeticamente descendente</option>

        </select>



        <button type="submit">Filtrar</button>
    </form>





    <!-- Page content-->
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <article>
                    <div class="post-container">
                        <h2>PUBLICACIONES</h2>

                       {% for post in posteos %}

                         <div class="card m-5">
                         <div class="card-header">
                          {{post.fecha}}
                         </div>
                            <div class="card mb-3">
                                
                                {% if post.imagen_url %}
                                <img src="{{ post.imagen_url }}" class="card-img-top" alt="...">  
                                
                                {% else %}
                                <img src="https://i0.wp.com/criptotendencia.com/wp-content/uploads/2023/03/DeFi.jpg?resize=890%2C450&ssl=1" class="card-img-top" alt="...">
                                {% endif %}
                                    

                              <div class="card-body">

                            <h5 class="card-title">{{post.titulo}}</h5>
                            <p class="card-text">{{post.post|truncatechars:400}}</p>
                            <p class="card-text">Categoría: {{post.categoria}}</p>
                  
                            <p class="card-text"><small class="text-body-secondary">Creado por: {{post.creador}}</small></p>
                            <a class="btn btn-primary" href="{% url 'publicaciones:detalle-post' post.pk %}" role="button">Detalles</a>
                            </div>

                            {% if user.is_superuser or user == user.es_colaborador %}
                              <a class="btn btn-outline-secondary" href="{% url 'publicaciones:editar-post' post.pk %}" role="button">Editar</a>
                              <a class="btn btn-outline-danger" href="{% url 'publicaciones:eliminar-post' post.pk %}" role="button">Eliminar</a>
                              
                   
                             {% endif %}

                             
                           </div> 
                         </div>
                        {% endfor %} 
                     </div> 





                 </article>
                <!-- ... Rest of the content ... -->
            </div>
            <!-- ... Rest of the content ... -->
        </div>
    </div>
   <!--Pagination-->

     

   {% if is_paginated %}

   <nav aria-label="Page navigation example" class="mt-5">
   
       <ul class="pagination">
   
   
           {% if page_obj.has_previous %}
               <li class="page-item">
                   <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                       <span aria-hidden="true">&laquo;</span>
                   </a>
               </li>
           {% else %}
               <li class="page-item">
                   <a class="page-link disabled" href="#" aria-label="Previous">
                       <span aria-hidden="true">&laquo;</span>
                   </a>
               </li>
   
           {% endif %}
               
                           
           {% for pagina in paginator.page_range %}
               <li class="page-item"><a class="page-link {% if page_obj.number == pagina %} active {% endif %}
                   " href="?page={{pagina}}">{{ pagina }}</a></li>
           {% endfor %}
               
                              
           {% if page_obj.has_next %}
               <li class="page-item">
                   <a class="page-link" href="?page= {{ page_obj.next_page_number }}" aria-label="Next">
                       <span aria-hidden="true">&raquo;</span>
                   </a>
               </li>
           {% else %}
               <li class="page-item">
                   <a class="page-link disabled" href="#" aria-label="Next">
                       <span aria-hidden="true">&raquo;</span>
                   </a>
               </li>
   
           {% endif %}
               
        
       </ul>
   </nav>
   
       
   {% endif %}
             
{% endblock contenido %}

        
    


    
        
    


       
 
=======
    
>>>>>>> editar_usuarios

src/templates/tokens.html
{% extends 'base.html' %}


{% load static %}

{% block contenido %}


<!DOCTYPE html>
<html lang="en">
    <head>

         <!-- Page content-->
         <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h5 class="fw-bolder mb-1">¿Qué son los tokens?</h5>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Publicado el 25 de Julio de 2023 by Javier</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="https://i.imgur.com/ZpZLUZ8.jpeg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">La palabra “token” es utilizada como otra manera de referirse a las criptomonedas, aunque en la actualidad, depende del contexto se utiliza para describir a ciertos activos digitales que se ejecutan sobre la cadena de bloques de otra criptomoneda.</p>
                            <p class="fs-5 mb-4">Estos pueden ser utilizados para crear casas de cambio descentralizadas hasta vender artículos poco comunes en videojuegos. También pueden ser intercambiados y almacenados como cualquier otra criptomoneda. </p>
                            <p class="fs-5 mb-4"></p>

                        </section>
                    </article>

                </div>



        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">GRUPO 1 - INFORMATORIO 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src=""></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>
{% endblock contenido %}