src/core/urls.py
from django.urls import path, include
from core import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.indexView, name = 'index'),
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('acercade/', views.acercadeView, name = 'acercade'),
    path ('defi/', views.defiView, name= 'defi'),
    path ('blockchains/', views.blockView, name='blockchains'),
    path ('tokens/', views.tokensView, name='tokens'),
    path ('trading/', views.tradingView, name='trading'),
    path('contacto/', include('contacto.urls')),
]

urlpatterns += staticfiles_urlpatterns ()

src/usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView,PasswordChangeView
from .views import RegistroView, EditarUsuario


app_name= 'usuarios'

urlpatterns=[
    path('login/',LoginView.as_view(template_name = 'usuarios/login.html'),name = 'login'),
    path('logout/', LogoutView.as_view(next_page=''),name = 'logout'),
    path('registrarse/', RegistroView.as_view(), name = 'registrarse'),
    path('editar_usuario/<int:pk>', EditarUsuario.as_view(),name = 'editar_usuario'),
    path('editar_contrasenia/<int:pk>', PasswordChangeView.as_view(template_name = 'usuarios/cambiar_contrasenia.html',success_url = '../../index'), name = 'cambiar_contrasenia')
]

src/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
#from django.contrib.auth.models import AbstractUser, Group, Permission


class Profile(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.usuario)
    
    def get_absolute_url(self):
        return reverse('index')
    
    

#class User(AbstractUser):
 #   groups = models.ManyToManyField(
  #      Group,
   #     verbose_name='groups',
    #    blank=True,
     #   help_text='The groups this user belongs to.',
      #  related_name='usuarios_users'  # Agrega related_name personalizado para evitar el conflicto
    #)
    #user_permissions = models.ManyToManyField(
     #   Permission,
      #  verbose_name='user permissions',
       # blank=True,
       # help_text='Specific permissions for this user.',
        #related_name='usuarios_users'  # Agrega related_name personalizado para evitar el conflicto
    #)

    #def __str__(self):
     #   return self.username

src/usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User 
from django import forms
from .models import User

from django.forms import ModelForm


class RegistrarseFrom(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta: 
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2' )

    def __init__(self, *args, **kwargs):
        super(RegistrarseFrom, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

class UserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')







class EditarUserForm(ModelForm):
    class Meta:
        model = User 
        fields = ['username','first_name', 'last_name', 'email']

src/usuarios/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView
from .forms import RegistrarseFrom
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth import login
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from .models import Profile
from .forms import UserChangeForm

from .forms import EditarUserForm

class LoginUsuario(LoginView):
    template_name = 'usuarios/login.html'


class RegistroView(CreateView):
    template_name = 'usuarios/registrarse.html'
    form_class = RegistrarseFrom
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        respuesta = super().form_valid(form)

        usuario = form.save()

        login(self.request, usuario)

        return respuesta

class ShowProfilePageView(DetailView):
	model = Profile
	template_name = 'registration/user_profile.html'

	def get_context_data(self, *args, **kwargs):
		#users = Profile.objects.all()
		context = super(ShowProfilePageView, self).get_context_data(*args, **kwargs)
		
		page_user = get_object_or_404(Profile, id=self.kwargs['pk'])

		context["page_user"] = page_user
		return context




class EditarUsuario(UpdateView, LoginRequiredMixin):
    model = User

    template_name = 'usuarios/editar_usuario.html'

    form_class = EditarUserForm


    def form_valid(self, form):

        respuesta = super().form_valid(form)
        usuario = form.save()

        login(self.request,usuario)

        return respuesta


    def get_success_url(self):
        return reverse('index')
    

    


    

src/templates/usuarios/cambiar_contrasenia.html
<!DOCTYPE html>
<html>
<head>
  <title>Editar Contraseña</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f0f0f0;
    }

    .custom-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 15px;
      max-width: 500px; /* Reducimos el ancho máximo del formulario */
      width: 100%;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Estilos para redondear los inputs de texto */
    .form-group input[type="text"],
    .form-group input[type="email"], /* Agregamos el selector para el input de correo electrónico */
    .form-group input[type="password"] {
      border-radius: 5px;
      border: 1px solid #ccc;
      padding: 2px; /* Reducimos el espacio interior de los inputs */
      width: 40%;
    }

    /* Estilo para redondear el botón y cambiar el color */
    .btn {
      border-radius: 5px;
      padding: 2px; /* Reducimos el espacio interior del botón */
    }

    /* Cambiamos el color del botón a un azul más claro */
    .btn-primary {
      background-color: #0062E6;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="custom-container">
    <div class="form-container">
      <h2 class="text-center mb-4">Editar Contraseña</h2>
      <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group">
        

              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>

            {{ field }}
            <div class="invalid-feedback">
              {{ field.errors }}
            </div>
          </div>
        {% endfor %}

        <!-- Usamos la clase .btn-primary para cambiar el color del botón -->
        <button type="submit" class="btn btn-primary btn-block mt-3">Guardar</button>
      </form>
    </div>
  </div>
</body>
</html>

src/templates/usuarios/cambiar_contraseña.html
<!DOCTYPE html>
<html>
<head>
  <title>Editar Contraseña</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f0f0f0;
    }

    .custom-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 15px;
      max-width: 500px; /* Reducimos el ancho máximo del formulario */
      width: 100%;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Estilos para redondear los inputs de texto */
    .form-group input[type="text"],
    .form-group input[type="email"], /* Agregamos el selector para el input de correo electrónico */
    .form-group input[type="password"] {
      border-radius: 5px;
      border: 1px solid #ccc;
      padding: 2px; /* Reducimos el espacio interior de los inputs */
      width: 40%;
    }

    /* Estilo para redondear el botón y cambiar el color */
    .btn {
      border-radius: 5px;
      padding: 2px; /* Reducimos el espacio interior del botón */
    }

    /* Cambiamos el color del botón a un azul más claro */
    .btn-primary {
      background-color: #0062E6;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="custom-container">
    <div class="form-container">
      <h2 class="text-center mb-4">Editar Contraseña</h2>
      <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group">
        

              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>

            {{ field }}
            <div class="invalid-feedback">
              {{ field.errors }}
            </div>
          </div>
        {% endfor %}

        <!-- Usamos la clase .btn-primary para cambiar el color del botón -->
        <button type="submit" class="btn btn-primary btn-block mt-3">Guardar</button>
      </form>
    </div>
  </div>
</body>
</html>

src/templates/usuarios/editar_usuario.html
<!DOCTYPE html>
<html>
<head>
  <title>Editar Usuario</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f0f0f0;
    }

    .custom-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 15px;
      max-width: 400px; /* Reducimos el ancho máximo del formulario */
      width: 100%;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Estilos para redondear los inputs de texto */
    .form-group input[type="text"],
    .form-group input[type="email"], /* Agregamos el selector para el input de correo electrónico */
    .form-group input[type="password"] {
      border-radius: 5px;
      border: 1px solid #ccc;
      padding: 2px; /* Reducimos el espacio interior de los inputs */
      width: 40%;
    }

    /* Estilo para redondear el botón y cambiar el color */
    .btn {
      border-radius: 5px;
      padding: 2px; /* Reducimos el espacio interior del botón */
    }

    /* Cambiamos el color del botón a un azul más claro */
    .btn-primary {
      background-color: #0062E6;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="custom-container">
    <div class="form-container">
      <h2 class="text-center mb-4">Editar Usuario</h2>
      <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group">
            {% if field.name == 'email' %}
              <label for="{{ field.id_for_label }}">Correo electronico</label>
            {% else %}
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {% endif %}
            {{ field }}
            <div class="invalid-feedback">
              {{ field.errors }}
            </div>
          </div>
        {% endfor %}

        <!-- Usamos la clase .btn-primary para cambiar el color del botón -->
        <button type="submit" class="btn btn-primary btn-block mt-3">Guardar Cambios</button>
        <a href="{% url 'usuarios:cambiar_contrasenia' user.id %}"> cambiar contraseña</a>
      </form>
    </div>
  </div>
</body>
</html>

src/templates/usuarios/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Inicio de Sesión</title>
    <style>
        /* Estilos CSS (mantenemos los estilos anteriores) */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .container {
            text-align: center;
            max-width: 400px;
            margin: 0 auto;
            padding: 50px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #555;
        }

        form {
            margin-top: 20px;
        }

        form label {
            display: block;
            margin-bottom: 5px;
            color: #333;
            font-size: 20px; /* Tamaño de fuente aumentado */
        }

        form input[type="text"],
        form input[type="password"] {
            width: 75%; /* Ancho al 100% para ocupar todo el espacio disponible */
            padding: 10px;
            margin-bottom: 10px; /* Reducido el margen inferior para separar menos los elementos */
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        form button[type="submit"] {
            text-align: center;
            margin-top: 20px;
            width: 50%;
            padding: 10px;
            background-color: #0062E6;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .register-link {
            display: inline-block;
            margin-top: 10px;
            width: 50%;
            padding: 10px;
            background-color: #b1b1b1;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px; /* Agregamos margen derecho para espaciado */
        }

        .register-link:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Iniciar Sesión</h2>
        <form method="post"> {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">Usuario</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="{{ form.password.id_for_label }}">Contraseña</label>
                {{ form.password }}
            </div>
            <button type="submit">Iniciar Sesión</button>
            <a href= "{% url 'usuarios:registrarse' %}" class="register-link">Registrarse</a>
        </form>
    </div>
</body>
</html>

src/templates/usuarios/registrarse.html
<!DOCTYPE html>
<html>
<head>
<<<<<<< HEAD
    <title>Registrarse</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 30px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #555;
        }

        form {
            margin-top: 20px;
        }

        form label {
            display: block;
            margin-bottom: 5px;
            color: #333;
            font-size: 18px;
        }

        form input[type="text"],
        form input[type="email"],
        form input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        form button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #0062E6;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

    </style>
</head>
<body>
    <div class="container">
        <h1>Registrarse</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Registrarse</button>
        </form>
    </div>
</body>
</html>
=======
  <title>Crear Usuario</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f0f0f0;
    }

    .custom-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 15px;
      max-width: 400px; /* Reducimos el ancho máximo del formulario */
      width: 100%;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Estilos para redondear los inputs de texto */
    .form-group input[type="text"],
    .form-group input[type="email"], /* Agregamos el selector para el input de correo electrónico */
    .form-group input[type="password"] {
      border-radius: 5px;
      border: 1px solid #ccc;
      padding: 2px; /* Reducimos el espacio interior de los inputs */
      width: 40%;
    }

    /* Estilo para redondear el botón y cambiar el color */
    .btn {
      border-radius: 5px;
      padding: 2px; /* Reducimos el espacio interior del botón */
    }

    /* Cambiamos el color del botón a un azul más claro */
    .btn-primary {
      background-color: #0062E6;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="custom-container">
    <div class="form-container">
      <h2 class="text-center mb-4">Crear Usuario</h2>
      <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group">
            {% if field.name == 'email' %}
              <label for="{{ field.id_for_label }}">Correo electronico</label>
            {% else %}
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {% endif %}
            {{ field }}
            <div class="invalid-feedback">
              {{ field.errors }}
            </div>
          </div>
        {% endfor %}

        <!-- Usamos la clase .btn-primary para cambiar el color del botón -->
        <button type="submit" class="btn btn-primary btn-block mt-3">Crear Cuenta</button>
      </form>
    </div>
  </div>
</body>
</html>
>>>>>>> editar_usuarios

src/templates/usuarios/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    

<h1>User Profile...</h1>
<br/>


<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-2">
{% if page_user.profile_pic %}
      <img src="{{ page_user.profile_pic.url }}" class="card-img">

{% else %}
	<img src="{% static 'theblog/images/default_profile_pic.png' %}" class="card-img">
{% endif %}
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h5 class="card-title">
        	{{ page_user.user.first_name }} 
			{{ page_user.user.last_name }}
		</h5>

<p class="small text-muted">
	
	

	{% if page_user.website_url %}
		 <a href="{{ page_user.website_url }}">  Website</a>  
	{% endif %}

	
	{% if page_user.facebook_url %}
		 | <a href="{{ page_user.facebook_url }}">Facebook</a>  
	{% endif %}


	{% if page_user.twitter_url %}
		| <a href="{{ page_user.twitter_url }}">Twitter</a> 
	{% endif %}


	{% if page_user.instagram_url %}
		| <a href="{{ page_user.instagram_url }}">Instagram</a>
	{% endif %}


	{% if page_user.pinterest_url %}
		| <a href="{{ page_user.pinterest_url }}">Pinterest</a>
	{% endif %}


</p>


<p class="card-text">
        	{{ page_user.bio }}
        </p>
        
      </div>
    </div>
  </div>
</div>

<br/><br/>




{% endblock %}